// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS1RcpcCg1bYMdK-pHnl-6u-ipiid6BSw',
    appId: '1:810877544598:web:ed48cdfcee94888b9b3ab7',
    messagingSenderId: '810877544598',
    projectId: 'redditclone-c704e',
    authDomain: 'redditclone-c704e.firebaseapp.com',
    storageBucket: 'redditclone-c704e.appspot.com',
    measurementId: 'G-L5RZX71G8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9nF0pTTKaDYQRpCdP3B4f0gbgb-f9RFc',
    appId: '1:810877544598:android:79b3edaff8f3687d9b3ab7',
    messagingSenderId: '810877544598',
    projectId: 'redditclone-c704e',
    storageBucket: 'redditclone-c704e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEdudSFNnUJZf6TaxAPi8DUkZFY_TxRxA',
    appId: '1:810877544598:ios:cfaf10730de5ca889b3ab7',
    messagingSenderId: '810877544598',
    projectId: 'redditclone-c704e',
    storageBucket: 'redditclone-c704e.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );
}
